SET QUOTED_IDENTIFIER ON

SET ANSI_NULLS OFF
GO
CREATE PROCEDURE [dbo].[ame_FFC_InsertSalesOrder]
@salesorder nvarchar(30),
@salesorderlineitem int,
@custmatnr nvarchar(50),
@serialprofile nvarchar(50),
@requestdate datetime,
@shipcond nvarchar(50),
@shipcondtxt nvarchar(50),
@soldto nvarchar(50),
@incoterms1 nvarchar(50),
@incoterms2 nvarchar(50),
@sdpymntterms nvarchar(50),
@customerpo nvarchar(50), 
@freightterms nvarchar(50),
@freighttermstxt nvarchar(50),
@DeliveryBlk nvarchar(50),
@DeliveryBlkTxt nvarchar(50),
@ShipTo nvarchar(50),
@Carrier nvarchar(50),
@AdrName1 nvarchar(50),
@AdrName2 nvarchar(50),
@AdrStreet nvarchar(50),
@AdrPostal nvarchar(50),
@AdrCity nvarchar(50),
@AdrState nvarchar(50),
@AdrCountry nvarchar(50),
@AdrFAX nvarchar(50),
@CountryDesc nvarchar(50),
@PurchaseOrder nvarchar(50),
@PurchaseItem int,
@Material nvarchar(50),
@PRDHA nvarchar(50),
@Qty int,
@UOM nvarchar(50),
@MatDescription nvarchar(50),
@PoPrice real ,
@TotalPrice real,
@RevisionLvl nvarchar(50),
@WAERS nvarchar(50),
@POPymntTerms nvarchar(50),
@POPymntTermsTxt nvarchar(50),
@Delivery datetime
AS


insert into FFC_SalesOrders
(
FFC_SO_SalesOrder, FFC_SO_SalesItem, 
FFC_SO_CustMatnr, FFC_SO_SerialProfile, FFC_SO_RequestDate,
 FFC_SO_ShipCond, FFC_SO_ShipCondType, FFC_SO_SoldTo, 
FFC_SO_INCOTERMS1, FFC_SO_INCOTERMS2,FFC_SO_SDPYMNTTERMS, FFC_SO_CUSTOMERPO,
 FFC_SO_FREIGHTTERMS, FFC_SO_FREIGHTTERMSTXT, FFC_SO_DELIVERYBLK, 
FFC_SO_DELIVERYBLKTXT, FFC_SO_SHIPTO, FFC_SO_CARRIER,
 FFC_SO_ADRNAME1, FFC_SO_ADRNAME2, FFC_SO_ADRSTREET, 
FFC_SO_ADRPOSTALCODE, FFC_SO_ADRCITY,FFC_SO_ADRSTATE, FFC_SO_ADRCOUNTRY, 
FFC_SO_ADRFAX, FFC_SO_ADRCOUNTRYDESC, FFC_SO_PURCHASEORDER, 
FFC_SO_PURCHASEITEM, FFC_SO_MATERIAL, FFC_SO_PRDHA, FFC_SO_QTY, 
FFC_SO_UOM, FFC_SO_MATDESCRIPTION, FFC_SO_POPRICE, 
FFC_SO_TOTALPRICE, FFC_SO_REVISIONLVL, FFC_SO_WAERS, 
FFC_SO_POPYMNTTERMS, FFC_SO_POPYMNTTERMSTXT, FFC_SO_DELIVERYDATE
)
values
(
@salesorder ,
@salesorderlineitem ,
@custmatnr ,
@serialprofile ,
@requestdate ,
@shipcond ,
@shipcondtxt ,
@soldto ,
@incoterms1 ,
@incoterms2,
@sdpymntterms ,
@customerpo , 
@freightterms ,
@freighttermstxt ,
@DeliveryBlk ,
@DeliveryBlkTxt ,
@ShipTo ,
@Carrier ,
@AdrName1 ,
@AdrName2 ,
@AdrStreet ,
@AdrPostal ,
@AdrCity ,
@AdrState,
@AdrCountry ,
@AdrFAX ,
@CountryDesc ,
@PurchaseOrder ,
@PurchaseItem ,
@Material ,
@PRDHA,
@Qty ,
@UOM ,
@MatDescription ,
@PoPrice  ,
@TotalPrice ,
@RevisionLvl ,
@WAERS ,
@POPymntTerms ,
@POPymntTermsTxt ,
@Delivery 
)

select 'OK'
GO