SET QUOTED_IDENTIFIER, ANSI_NULLS OFF
GO
CREATE PROCEDURE [dbo].[ame_FFCgetLiteLimits] AS
set nocount on


select 
FFC_SO_SalesOrder, FFC_SO_SalesItem, 
FFC_SO_CustMatnr, FFC_SO_SerialProfile, FFC_SO_RequestDate, 
FFC_SO_ShipCond, FFC_SO_ShipCondType, FFC_SO_SoldTo, 
FFC_SO_INCOTERMS, FFC_SO_SDPYMNTTERMS, FFC_SO_CUSTOMERPO, 
FFC_SO_FREIGHTTERMS, FFC_SO_FREIGHTTERMSTXT, FFC_SO_DELIVERYBLK, 
FFC_SO_DELIVERYBLKTXT, FFC_SO_SHIPTO, FFC_SO_CARRIER, 
FFC_SO_ADRNAME1, FFC_SO_ADRNAME2, FFC_SO_ADRSTREET, 
FFC_SO_ADRPOSTALCODE, FFC_SO_ADRCITY, FFC_SO_ADRCOUNTRY, 
FFC_SO_ADRFAX, FFC_SO_ADRCOUNTRYDESC, FFC_SO_PURCHASEORDER, 
FFC_SO_PURCHASEITEM, FFC_SO_MATERIAL, FFC_SO_QTY, 
FFC_SO_UOM, FFC_SO_MATDESCRIPTION, FFC_SO_POPRICE, 
FFC_SO_TOTALPRICE, FFC_SO_REVISIONLVL, FFC_SO_WAERS, 
FFC_SO_POPYMNTTERMS, FFC_SO_POPYMNTTERMSTXT, FFC_SO_DELIVERYDATE
from FFC_SalesOrders
GO