SET QUOTED_IDENTIFIER, ANSI_NULLS OFF
GO
CREATE PROCEDURE  [dbo].[ame_TFFC_GetKickerTable]
AS
set nocount on
select TFFC_KICKER_ID, TFFC_KICKER_Station, TFFC_KICKER_Model, TFFC_KICKER_DESCRIPTION,TFFC_KICKER_TestType, TFFC_KICKER_RunPath, TFFC_KICKER_DBPath, 
TFFC_KICKER_SerialPortConfig, TFFC_KICKER_QBUDDIES, 
TFFC_KICKER_TMParameters, TFFC_KICKER_TMCodice, TFFC_KICKER_Rework, TFFC_KICKER_BinarySerialPortConfig from TFFC_KICKER_TABLE
GO