SET QUOTED_IDENTIFIER, ANSI_NULLS OFF
GO
CREATE PROCEDURE [dbo].[ame_FFC_EUG_GetSalesOrders]
@Vendor char(20),
@Plant char(10)
 AS
set nocount on
if not exists (select FFC_NOPRICE_ID from FFC_NOPRICE where FFC_NOPRICE_Vendor = @Vendor and FFC_NOPRICE_Plant = @Plant)
begin
select 
FFC_SO_SalesOrder, 
FFC_SO_SalesItem, FFC_SO_CustMatnr, FFC_SO_SerialProfile,
 FFC_SO_RequestDate, FFC_SO_ShipCond, FFC_SO_ShipCondType, 
FFC_SO_SoldTo, FFC_SO_INCOTERMS1, FFC_SO_INCOTERMS2, 
FFC_SO_SDPYMNTTERMS, FFC_SO_CUSTOMERPO, FFC_SO_FREIGHTTERMS, 
FFC_SO_FREIGHTTERMSTXT, FFC_SO_DELIVERYBLK, FFC_SO_DELIVERYBLKTXT,
 FFC_SO_SHIPTO, FFC_SO_CARRIER, FFC_SO_ADRNAME1, 
FFC_SO_ADRNAME2, FFC_SO_ADRSTREET, FFC_SO_ADRPOSTALCODE, 
FFC_SO_ADRCITY, FFC_SO_ADRSTATE, FFC_SO_ADRCOUNTRY, 
FFC_SO_ADRFAX, FFC_SO_ADRTEL, FFC_SO_ADRCOUNTRYDESC, 
FFC_SO_PURCHASEORDER, FFC_SO_PURCHASEITEM, FFC_SO_MATERIAL, 
FFC_SO_PRDHA, FFC_SO_QTY, FFC_SO_UOM, 
FFC_SO_MATDESCRIPTION, FFC_SO_POPRICE, FFC_SO_TOTALPRICE,
 FFC_SO_REVISIONLVL, FFC_SO_WAERS, FFC_SO_POPYMNTTERMS, 
FFC_SO_POPYMNTTERMSTXT, FFC_SO_DELIVERYDATE
from FFC_EUG_SalesOrders
where rtrim(FFC_SO_Vendor) = rtrim(@Vendor) and rtrim(FFC_SO_Plant)= rtrim(@Plant)
end
else
begin
select 
FFC_SO_SalesOrder, 
FFC_SO_SalesItem, FFC_SO_CustMatnr, FFC_SO_SerialProfile,
 FFC_SO_RequestDate, FFC_SO_ShipCond, FFC_SO_ShipCondType, 
FFC_SO_SoldTo, FFC_SO_INCOTERMS1, FFC_SO_INCOTERMS2, 
FFC_SO_SDPYMNTTERMS, FFC_SO_CUSTOMERPO, FFC_SO_FREIGHTTERMS, 
FFC_SO_FREIGHTTERMSTXT, FFC_SO_DELIVERYBLK, FFC_SO_DELIVERYBLKTXT,
 FFC_SO_SHIPTO, FFC_SO_CARRIER, FFC_SO_ADRNAME1, 
FFC_SO_ADRNAME2, FFC_SO_ADRSTREET, FFC_SO_ADRPOSTALCODE, 
FFC_SO_ADRCITY, FFC_SO_ADRSTATE, FFC_SO_ADRCOUNTRY, 
FFC_SO_ADRFAX, FFC_SO_ADRTEL, FFC_SO_ADRCOUNTRYDESC, 
FFC_SO_PURCHASEORDER, FFC_SO_PURCHASEITEM, FFC_SO_MATERIAL, 
FFC_SO_PRDHA, FFC_SO_QTY, FFC_SO_UOM, 
FFC_SO_MATDESCRIPTION,  cast(0.0 as real) as FFC_SO_POPRICE,  cast(0.0 as real) as FFC_SO_TOTALPRICE,
 FFC_SO_REVISIONLVL, FFC_SO_WAERS, FFC_SO_POPYMNTTERMS, 
FFC_SO_POPYMNTTERMSTXT, FFC_SO_DELIVERYDATE
from FFC_EUG_SalesOrders
where rtrim(FFC_SO_Vendor) = rtrim(@Vendor) and rtrim(FFC_SO_Plant)= rtrim(@Plant)
end
GO