CREATE TABLE [dbo].[DAY2TRANS] (
  [DAY2TRANS_ID] [int] IDENTITY,
  [DAY2TRANS_MTYP] [char](10) NULL,
  [DAY2TRANS_MATERIAL] [char](20) NULL,
  [DAY2TRANS_DESCRIPTION] [char](40) NULL,
  [DAY2TRANS_ACTUALSAP] [char](20) NULL,
  [DAY2TRANS_NEWCODE] [char](20) NULL,
  [DAY2TRANS_GERACHIA] [char](20) NULL,
  [DAY2TRANS_USEDINBOM] [char](20) NULL,
  [DAY2TRANS_BOM] [char](20) NULL,
  [DAY2TRANS_PLANTSTATUS] [char](20) NULL,
  CONSTRAINT [PK_DAY2TRANS] PRIMARY KEY CLUSTERED ([DAY2TRANS_ID])
)
ON [PRIMARY]
GO