CREATE TABLE [dbo].[BCSBACKUP_BCSSTEPRELATIONS] (
  [STEPRELATE_id] [int] NOT NULL,
  [STEPRELCHILD_id] [int] NULL,
  [STEPRELDISPLAY] [int] NULL,
  [STEPRELOTHER] [nchar](10) NULL
)
ON [PRIMARY]
GO