CREATE TABLE [dbo].[PANSTLTODB1MAP] (
  [PTDSTL_ID] [int] IDENTITY,
  [PANSTL_ID] [int] NULL,
  [DB1STL_ID] [int] NULL,
  [Transfer_Time] [datetime] NULL,
  CONSTRAINT [PK_PANSTLTODB1MAP] PRIMARY KEY CLUSTERED ([PTDSTL_ID])
)
ON [PRIMARY]
GO