CREATE TABLE [dbo].[PHRASETRANSLATE] (
  [PHRASE_ID] [int] IDENTITY,
  [PHRASE_KEY] [char](20) NULL,
  [PHRASE_STATION] [char](50) NULL,
  [PHRASE_DESCRIPTION] [char](255) NULL,
  [PHRASE_TYPE] [char](50) NULL,
  [PHRASE_ENGLISH] [char](255) NULL,
  [PHRASE_FOREIGN] [nvarchar](255) NULL,
  CONSTRAINT [PK_Phrase_Translate] PRIMARY KEY CLUSTERED ([PHRASE_ID]) WITH (FILLFACTOR = 80)
)
ON [PRIMARY]
GO