CREATE TABLE [dbo].[FFC_Configuration] (
  [FFC_Config_ID] [int] IDENTITY,
  [FFC_NextRunDateTime] [datetime] NULL,
  [FFC_DSO] [tinyint] NULL,
  [FFC_DLimits] [tinyint] NULL,
  [FFC_DBOMs] [tinyint] NULL,
  [FFC_DFiles] [tinyint] NULL,
  [FFC_UStatus] [tinyint] NULL,
  [FFC_UAssembly] [tinyint] NULL,
  [FFC_UTestlog] [tinyint] NULL,
  [FFC_LastRunDate] [datetime] NULL,
  [FFC_AdminSchedule] [int] NULL,
  [FFC_Recur_Occurs] [int] NULL,
  [FFC_Daily_Days] [int] NULL,
  [FFC_Monthly_Day] [int] NULL,
  [FFC_Monthly_Month] [int] NULL,
  [FFC_Weekly_Freq] [int] NULL,
  [FFC_Mon] [tinyint] NULL,
  [FFC_tue] [tinyint] NULL,
  [FFC_wed] [tinyint] NULL,
  [FFC_Thur] [tinyint] NULL,
  [FFC_Fri] [tinyint] NULL,
  [FFC_Sat] [tinyint] NULL,
  [FFC_Sun] [tinyint] NULL,
  [FFC_DailyFreq] [int] NULL,
  [FFC_DailyFreq_Time] [datetime] NULL,
  [FFC_DailyFreq_Interval] [int] NULL,
  [FFC_StartDate] [datetime] NULL,
  [FFC_Ending] [int] NULL,
  [FFC_EndDateTIme] [datetime] NULL,
  [FFC_OneTimeDateTime] [datetime] NULL,
  [FFC_LastActualRunDate] [datetime] NULL,
  CONSTRAINT [PK_FFC_Configuration] PRIMARY KEY CLUSTERED ([FFC_Config_ID])
)
ON [PRIMARY]
GO