CREATE TABLE [dbo].[VNTFFC_KICKER_TABLE] (
  [TFFC_KICKER_ID] [int] IDENTITY,
  [TFFC_KICKER_STATION] [char](20) NULL,
  [TFFC_KICKER_MODEL] [char](20) NULL,
  [TFFC_KICKER_DESCRIPTION] [char](80) NULL,
  [TFFC_KICKER_TESTTYPE] [char](20) NULL,
  [TFFC_KICKER_RUNPATH] [char](80) NULL,
  [TFFC_KICKER_DBPATH] [char](80) NULL,
  [TFFC_KICKER_SERIALPORTCONFIG] [char](120) NULL,
  [TFFC_KICKER_BINARYSERIALPORTCONFIG] [char](50) NULL,
  [TFFC_KICKER_QBUDDIES] [char](20) NULL,
  [TFFC_KICKER_TMPARAMETERS] [char](80) NULL,
  [TFFC_KICKER_TMCODICE] [char](40) NULL,
  [TFFC_KICKER_REWORK] [int] NULL,
  CONSTRAINT [PK_VNTFFC_KICKER_TABLE] PRIMARY KEY CLUSTERED ([TFFC_KICKER_ID])
)
ON [PRIMARY]
GO