CREATE TABLE [dbo].[TRN_Stations] (
  [Station_Count] [int] NOT NULL,
  [Station_Name] [char](20) NOT NULL,
  [Description] [nchar](40) NULL CONSTRAINT [DF_TRN_Stations_Description] DEFAULT (null),
  [ACS_Serial_ID] [char](2) NULL CONSTRAINT [DF_TRN_Stations_ACS_Serial_ID] DEFAULT (null),
  [Gen_PSC_Serial] [char](1) NULL CONSTRAINT [DF_TRN_Stations_Gen_PSC_Serial] DEFAULT (null),
  [Print_Asm_Label] [char](1) NULL CONSTRAINT [DF_TRN_Stations_Print_Asm_Label] DEFAULT (null),
  [Print_Unit_Label] [char](1) NULL CONSTRAINT [DF_TRN_Stations_Print_Unit_Label] DEFAULT (null),
  [Print_Carton_Label] [char](1) NULL CONSTRAINT [DF_TRN_Stations_Print_Carton_Label] DEFAULT (null),
  [Print_Extra_label] [char](1) NULL CONSTRAINT [DF_TRN_Stations_Print_Extra_label] DEFAULT (null),
  [Allow_Overrides] [char](1) NULL CONSTRAINT [DF_TRN_Stations_Allow_Overrides] DEFAULT (null),
  [Finish_Assembly] [char](1) NULL CONSTRAINT [DF_TRN_Stations_Finish_Assembly] DEFAULT (null),
  [Perform_Test] [char](1) NULL CONSTRAINT [DF_TRN_Stations_Perform_Test] DEFAULT (null),
  [Assign_Sales_Order] [char](1) NULL CONSTRAINT [DF_TRN_Stations_Assign_Sales_Order] DEFAULT (null),
  [Backflush] [char](1) NULL CONSTRAINT [DF_TRN_Stations_Backflush] DEFAULT (null),
  [Status] [char](1) NOT NULL CONSTRAINT [DF_TRN_Stations_Status] DEFAULT ('A'),
  [Machine_Name] [char](30) NULL,
  [FactoryGroup_Mask] [int] NULL,
  [ProductGroup_Mask] [int] NULL,
  [Order_Value] [int] NULL,
  [Thin_Client] [char](1) NULL,
  [Station_Type] [char](3) NULL,
  [Waterfall_Server_Machine_Name] [char](20) NULL,
  [Application_Server_Machine_Name] [char](20) NULL,
  [Business_Server_Machine_Name] [char](20) NULL,
  [STN_MfgLine_ID] [int] NULL CONSTRAINT [DF_TRN_Stations_STN_MfgLine_ID] DEFAULT (1000),
  [SPCEnabled] [char](1) NULL,
  [SAPLocationIndex] [int] NULL,
  [SAPLocationName] [char](20) NULL,
  CONSTRAINT [PK_TRN_Stations] PRIMARY KEY CLUSTERED ([Station_Count])
)
ON [PRIMARY]
GO