CREATE TABLE [dbo].[ELGINPN] (
  [ELGINPN_ID] [int] IDENTITY,
  [ELGINPN_HIERDESC] [char](80) NULL,
  [ELGINPN_COMPONENT] [char](30) NULL,
  [ELGINPN_COMPDESC] [char](80) NULL,
  [ELGINPN_NEWPN] [char](30) NULL,
  [ELGINPN_NEWDESC] [char](80) NULL,
  CONSTRAINT [PK_ELGINPN] PRIMARY KEY CLUSTERED ([ELGINPN_ID])
)
ON [PRIMARY]
GO