CREATE TABLE [dbo].[MosaicQueryTableResults] (
  [acs_serial] [char](20) NULL,
  [model] [char](20) NULL,
  [station] [char](20) NULL,
  [subtest] [char](20) NULL,
  [testid] [char](50) NULL,
  [passfail] [char](10) NULL,
  [testpassfail] [char](10) NULL,
  [strvalue] [char](80) NULL,
  [intvalue] [int] NULL,
  [floatvalue] [float] NULL,
  [units] [char](20) NULL,
  [stlid] [int] NULL,
  [comment] [char](80) NULL,
  [firstrun] [char](10) NULL,
  [testdatetime] [datetime] NULL,
  [mode] [int] NULL,
  [LimitStation] [char](30) NULL,
  [LimitSubtestname] [char](30) NULL,
  [LimitModel] [char](30) NULL,
  [LimitType] [char](10) NULL,
  [UL] [float] NULL,
  [LL] [float] NULL,
  [strLimit] [char](80) NULL,
  [flgLimit] [char](20) NULL,
  [LimitUnits] [char](20) NULL,
  [Description] [char](120) NULL,
  [Author] [char](120) NULL,
  [ACSEEMode] [int] NULL,
  [SPCParm] [char](10) NULL,
  [Hard_UL] [float] NULL,
  [Hard_LL] [float] NULL,
  [LimitDate] [datetime] NULL
)
ON [PRIMARY]
GO