CREATE TABLE [dbo].[SERIALBOXHISTORY] (
  [SERIALBOX_ID] [int] IDENTITY,
  [SERIALBOX_SerialID] [int] NULL,
  [SERIALBOX_BoxID] [int] NULL,
  [SERIALBOX_Reason] [char](20) NULL,
  [SERIALBOX_Date] [datetime] NULL,
  CONSTRAINT [PK_SERIALBOXHISTORY] PRIMARY KEY CLUSTERED ([SERIALBOX_ID]) WITH (FILLFACTOR = 80)
)
ON [PRIMARY]
GO

ALTER TABLE [dbo].[SERIALBOXHISTORY] WITH NOCHECK
  ADD CONSTRAINT [FK_SERIALBOXHISTORY_BOXNUMBER] FOREIGN KEY ([SERIALBOX_BoxID]) REFERENCES [dbo].[BOXNUMBER] ([BOXNUMBER_ID]) NOT FOR REPLICATION
GO

ALTER TABLE [dbo].[SERIALBOXHISTORY]
  NOCHECK CONSTRAINT [FK_SERIALBOXHISTORY_BOXNUMBER]
GO

ALTER TABLE [dbo].[SERIALBOXHISTORY] WITH NOCHECK
  ADD CONSTRAINT [FK_SERIALBOXHISTORY_TFFC_SerialNumbers] FOREIGN KEY ([SERIALBOX_SerialID]) REFERENCES [dbo].[TFFC_SerialNumbers] ([TFFC_ID]) NOT FOR REPLICATION
GO

ALTER TABLE [dbo].[SERIALBOXHISTORY]
  NOCHECK CONSTRAINT [FK_SERIALBOXHISTORY_TFFC_SerialNumbers]
GO